# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/eexyh39/OneDrive/FPGA_Project/EEEE4123/CW/VivadoPrj/MatrixProcessingCore_32x32_16bits/MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x16/dpram_1024x16.xci
# IP: The module: 'dpram_1024x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eexyh39/OneDrive/FPGA_Project/EEEE4123/CW/VivadoPrj/MatrixProcessingCore_32x32_16bits/MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x16/dpram_1024x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_1024x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/eexyh39/OneDrive/FPGA_Project/EEEE4123/CW/VivadoPrj/MatrixProcessingCore_32x32_16bits/MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x16/dpram_1024x16.xci
# IP: The module: 'dpram_1024x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eexyh39/OneDrive/FPGA_Project/EEEE4123/CW/VivadoPrj/MatrixProcessingCore_32x32_16bits/MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x16/dpram_1024x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_1024x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
