# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr_IntMatProCore_32x32_16bits.xdc

# IP: ip/dpram_1024x64/dpram_1024x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpram_1024x64 || ORIG_REF_NAME==dpram_1024x64} -quiet] -quiet
