######################################################################
#
# File name : tb_IntMatProCore_compile.do
# Created on: Mon Apr 10 00:48:17 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.6c\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.6c\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.6c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.6c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.6c\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x64/dpram_1024x64_sim_netlist.vhdl" \
"../../../../MatrixProcessingCore_32x32_16bits.srcs/sources_1/ip/dpram_1024x16/dpram_1024x16_sim_netlist.vhdl" \
"../../../../MatrixProcessingCore_32x32_16bits.srcs/sources_1/new/IntMatProCore_32x32_16bits.vhd" \
"../../../../MatrixProcessingCore_32x32_16bits.srcs/sim_1/new/tb_IntMatProCore_32x32_16bits.vhd" \


quit -force

